[ADD] list 페이지 sort 조건에 따른 product 배열 반환 API 구현
wecode-bootcamp-korea/38-2nd-KRWEAM-backend pull request #12
Opened 2022-11-07 13:36 UTC by c0zyb1ue

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-11-08 07:37 UTC, kyeongraekim requested changes

2022-11-08 07:37 UTC, kyeongraekim commented on controllers/productController.js
> +     if(limit) Limit=limit/1;
해당부분은 불필요한 하드코딩으로 보여집니다. 어떤 의미를 담고 있는지 코멘트로 설명주세요!

2022-11-08 07:37 UTC, kyeongraekim commented on services/productService.js
> +module.exports = { getNewProducts, getApplicableProducts }
해당 부분 코드의 의미는 구두로 설명 들으러 갈게요!~

2022-11-08 11:20 UTC, c0zyb1ue commented on controllers/productController.js
> +     if(limit) Limit=limit/1;
프론트에서 offset, limit을 query parameter에 담아주지 않아도 16개의 product만 반환하게 해달라고 해서 Offset Limit 이라는 변수에 미리 0, 16 값을 저장해 놓고, offset limit에 query parameter로 값이 들어온다면 변수에 해당 값을 재할당해주는 로직입니다.

2022-11-08 11:23 UTC, c0zyb1ue commented on services/productService.js
> +module.exports = { getNewProducts, getApplicableProducts }
넵 !

2022-11-09 06:43 UTC, kyeongraekim requested changes

2022-11-09 06:43 UTC, kyeongraekim commented on controllers/productController.js
> +     if(limit) Limit=limit/1;
```javascript
function isInt(value) {
    var er = /^-?[0-9]+$/;
    return er.test(value);
}

2022-11-10 01:33 UTC, kyeongraekim requested changes

2022-11-10 01:33 UTC, kyeongraekim commented on routers/userRouter.js
> +//router.get('/auth/kakao', userController.kakaoAuth);
불필요한 주석문은 삭제해주세요! 추후에 추가할 기능이라면 다른 브랜치를 푸시하여 해당 기능을 추가할 때 함께 녹여주셔야 합니다.

2022-11-10 05:58 UTC, kyeongraekim approved these changes

2022-11-10 05:58 UTC, merged