[ADD] 소셜 로그인 및 회원가입/로그인 API 구현
wecode-bootcamp-korea/38-2nd-KRWEAM-backend pull request #8
Opened 2022-11-04 09:03 UTC by c0zyb1ue

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-11-08 07:24 UTC, kyeongraekim requested changes

2022-11-08 07:24 UTC, kyeongraekim commented on services/userService.js
> +	const saltRounds = 10; // ~10 hashes/sec
이곳 포함 전반에 걸쳐 코드독해로 의미가 파악한 부분에 달려있는 불필요한 코드 주석은 삭제해주세요!~

2022-11-08 07:24 UTC, kyeongraekim commented on services/userService.js
> +	const salt       = await bcrypt.genSalt(saltRounds);
함수의 변수명은 동작의 행위가 담겨있어야 함으로 generateSalt정도로 수정해주시면 더 좋을 것 같습니다!~

2022-11-08 07:24 UTC, kyeongraekim commented on services/userService.js
> +     try{//access정보를 가지고 또 요청해야 정보를 가져올 수 있음.
이곳도 불필요한 주석 삭제해주세요!~

2022-11-08 07:24 UTC, kyeongraekim commented on routers/userRouter.js
> +//router.get('/auth/kakao', userController.kakaoAuth);
해당 부분은 사용되는 코드 로직일까요?

2022-11-08 07:24 UTC, kyeongraekim commented on services/userService.js
> +	const passwordRegex =/^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#\$%\^&\*])(?=.{8,})/
해당 내용은 아래 signIn 에도 동일하게 쓰이는 부분이며, 중복으로 선언이 되어지네요! 파일 제일 첫 머리 단에 상수 데이터로써 관리한다면 더 경제적인 사용이 될 것 같습니다!

2022-11-08 08:02 UTC, c0zyb1ue commented on services/userService.js
> +	const salt       = await bcrypt.genSalt(saltRounds);
genSalt 함수는 bcrypt 내장함수로 이해하고 있어서 generateSalt로 변경하면 안될 것 같은데 어떻게 해야할까요?

2022-11-08 08:03 UTC, c0zyb1ue commented on routers/userRouter.js
> +//router.get('/auth/kakao', userController.kakaoAuth);
백앤드 단에서만 통신 테스트를 할 떄 사용되는 부분입니다.

2022-11-09 06:32 UTC, kyeongraekim approved these changes
LGTM!~

2022-11-09 06:32 UTC, merged