[38기 김택수] ADD : 마이페이지 구매내역 및 판매내역 조회 완료
wecode-bootcamp-korea/38-2nd-KRWEAM-backend pull request #9
Opened 2022-11-05 07:30 UTC by Robinkim93

- 프론트엔드에서 데이터구조 요청한 부분들 반영완료

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 마이페이지 내 구매 및 판매내역 데이터 반환기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 구매내역 반환
- 현재 크림에는 구매입찰, 구매완료 두 가지 상태가 존재하며, 두 개의 테이블에서 구매유저로 등록되어있는 id값을 찾아 데이터를 반환한다. (product 정보)

2. 판매내역 반환
- 판매 또한 판매입찰, 판매완료 두 가지 상태이며, 똑같이 product 정보를 반환한다.

3. 데이터 구조 변경
- 프론트엔드에서 요청한 데이터구조대로 변경하여 반환할 수 있도록 service단에서 데이터 구조 변경

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-11-08 07:29 UTC, kyeongraekim requested changes

2022-11-08 07:29 UTC, kyeongraekim commented on package.json
> +    "httpie": "^1.1.2",
해당내용은 개발 환경에서 쓰이는 내용임으로 devDependencies에서 관리하는 것이 더 옳아 보입니다.

2022-11-08 07:29 UTC, kyeongraekim commented on services/mypageService.js
> +          status: "입찰 중",
해당 내용은 status를 정수값으로 관리한다면 실제 워딩이 아닌 statusCode를 주고 받는 것은 어떨까요?

2022-11-08 07:29 UTC, kyeongraekim commented on services/mypageService.js
> +const searchDealHistories = async (userId) => {
전반적으로 search의 워딩을 적어주셨는데 실질적인 검색의 기능과 추후에 혼동을 줄 여지가 있어 보입니다. 확장성 있는 변수명을 고려하여 get의 워딩이 더 옳아보입니다~

2022-11-08 08:45 UTC, Robinkim93 commented on services/mypageService.js
> +          status: "입찰 중",
해당 내용 바로 렌더링하기 위해서 적어준 것인데 수정하여서 프론트단에서 분기처리하는것이 좋을까요?

2022-11-09 06:33 UTC, kyeongraekim approved these changes

2022-11-09 06:33 UTC, kyeongraekim commented on services/mypageService.js
> +          status: "입찰 중",
프론트와의 기획까지 미리 변경되었으면 좋겠지만 시간이 부족하실 것 같으니 일단은 현재처럼 진행하겠습니다!~

2022-11-09 06:33 UTC, merged